<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net10.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
        <DockerDefaultTargetOS>Linux</DockerDefaultTargetOS>
    </PropertyGroup>

    <ItemGroup>
      <Folder Include="Common\Behaviours\" />
      <Folder Include="Common\DTO\" />
      <Folder Include="Common\Exceptions\" />
      <Folder Include="Common\Interfaces\" />
      <Folder Include="Common\Security\" />
    </ItemGroup>

    <ItemGroup>
      <Content Include="..\.dockerignore">
        <Link>.dockerignore</Link>
      </Content>
    </ItemGroup>

    <ItemGroup>
      <ProjectReference Include="..\Domain\Domain.csproj" />
    </ItemGroup>

    <ItemGroup>
      <PackageReference Include="AutoMapper" Version="14.0.0" />
      <PackageReference Include="FluentValidation.DependencyInjectionExtensions" Version="12.1.1" />
      <PackageReference Include="MediatR" Version="12.5.0" />
      <PackageReference Include="Microsoft.EntityFrameworkCore" Version="10.0.10" />
    </ItemGroup>

</Project>
